#!/bin/bash
## Set version of latest eos image
EOS_VERSION=4.6.5

docker push owncloud/eos-base:$EOS_VERSION
docker push owncloud/eos-qdb:$EOS_VERSION
docker push owncloud/eos-mgm:$EOS_VERSION
docker push owncloud/eos-mq:$EOS_VERSION
docker push owncloud/eos-fst:$EOS_VERSION

docker push owncloud/eos-ocis:latest
docker push owncloud/eos-ocis:master
docker push owncloud/eos-ocis-dev:latest
